### ISSUE TITLE
MultiMc instance wont start

### ISSUE THREAD

**Issue by strau0106** [shedaniel/LightOverlay-Fabric#20]
Minecraft process ID: 20961

Using onesix launcher.

[21:43:25] [main/INFO]: Loading for game Minecraft 1.15.1
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.UnsupportedOperationException: Call the solve method first!!!
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.model(Solver.java:498)
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:224)
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:603)
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:176)
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:166)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
Exiting with -1
Process exited with code 255.
Thanks for any further advise

**Comment by shedaniel** [comment]
Fabric loader issue, please report it there.
