### ISSUE TITLE
Crashing on load for 1.15.2 with Fabric

### ISSUE THREAD

**Issue by joelra** [shedaniel/LightOverlay-Fabric#27]
Game Version: 1.15.2
Light Overlay Version: 4.2

Using MultiMC version 0.6.8-1419, Fabric 1.15.2, I receive the following error:

```
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:55)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:34)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:392)
	at net.minecraft.client.main.Main.main(Main.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
	Suppressed: java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/client/keybinding/KeyBindingRegistryImpl
		at me.shedaniel.lightoverlay.fabric.LightOverlay.onInitializeClient(LightOverlay.java:228)
		at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:48)
		... 19 more
	Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.impl.client.keybinding.KeyBindingRegistryImpl
		at java.net.URLClassLoader.findClass(Unknown Source)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:161)
		at java.lang.ClassLoader.loadClass(Unknown Source)
		... 21 more
```

The prevalent part appears to be Suppressed: java.lang.NoClassDefFoundError: net/fabricmc/fabric/impl/client/keybinding/KeyBindingRegistryImpl
		at me.shedaniel.lightoverlay.fabric.LightOverlay.onInitializeClient(LightOverlay.java:228)

Unsure if that's something on my end or not.

**Comment by shedaniel** [comment]
Fixed in v4.3, releasing update soon.
