### ISSUE TITLE
Crash on 20w14a

### ISSUE THREAD

**Issue by Cretezy** [shedaniel/LightOverlay-Fabric#31]
```
java.lang.NoSuchFieldError: field_15463
	at me.shedaniel.lightoverlay.fabric.LightOverlay.getCrossType(LightOverlay.java:72)
	at me.shedaniel.lightoverlay.fabric.LightOverlay.lambda$onInitializeClient$11(LightOverlay.java:307)
	at net.minecraft.class_761.handler$zij000$renderCenter(class_761.java:4951)
	at net.minecraft.class_761.method_22710(class_761.java:1265)
	at net.minecraft.class_757.method_3188(class_757.java:718)
	at net.minecraft.class_757.method_3192(class_757.java:543)
	at net.minecraft.class_310.method_1523(class_310.java:1004)
	at net.minecraft.class_310.method_1514(class_310.java:632)
	at net.minecraft.client.main.Main.main(Main.java:204)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

Let me know if I can help in any way!

**Comment by shedaniel** [comment]
20w14a changed how tags function because Mojang decided to rewrite tags when they found a bug in it, the most logical solution to fixing the bug is to rewrite it entirely. I will update Light Overlay to it soon after updating other mods.

**Comment by Cretezy** [comment]
Mind keeping this issue open just for tracking when it's fixes? Would greatly simplify my workflow and might avoid more issues related to this issue

**Comment by shedaniel** [comment]
Sure.

**Comment by shedaniel** [comment]
Updated to 20w14a.
