### ISSUE TITLE
Startup Crash Forge 1.16.2

### ISSUE THREAD

**Issue by LunarLynx22085** [shedaniel/LightOverlay-Fabric#60]
Hello, i am currently having issues with the mod crashing in 1.16, please fix heres the code

https://docs.google.com/document/d/1QhMFdH_K_WsQ65eJoMjB2aJqSgpu5yShirlKcWUHiic/edit?usp=sharing

**Comment by Cryptic318** [comment]
Am also receiving the same error, with or without Optifine in the mods folder.

[crash-2020-09-08_10.03.00-client.txt](https://github.com/shedaniel/LightOverlay/files/5189130/crash-2020-09-08_10.03.00-client.txt)

**Comment by shedaniel** [comment]
Thanks for reporting, I will look into this issue soon!

**Comment by shedaniel** [comment]
I have failed to reproduce, can you try installing latest forge and cloth config?

**Comment by zergar** [comment]
I've had the same issue while using MC 1.16.2 with Forge 33.0.42 and both LightOverlay 5.5.2 and 5.5.3, though I haven't had cloth installed. So probably this is / was an issue with showing the "Missing Cloth"-Error Message. The issue disappeared for me after updating to Forge 33.0.61. (Though i was unable to close the Cloth-Error Message, as MC hung up in this screen).

Edit: After looking at the logs again, the explanation of missing Cloth Config would make perfect sense, as this overlay looked not that default for me. The issue appeared at the end of the loading process. 

For completeness sake, the Error Log:

```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 10/09/2020, 21:24
Description: Rendering overlay

java.lang.NullPointerException: Rendering overlay
	at net.minecraft.crash.CrashReportCategory.applyStackTrace(CrashReportCategory.java:164) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$3(CrashReportExtender.java:87) ~[?:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:78) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:191) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:494) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.Util.func_215077_a(SourceFile:404) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:490) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) ~[1.16.2-forge-33.0.42.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.2-33.0.42.jar:33.0] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.crash.CrashReportCategory.applyStackTrace(CrashReportCategory.java:164)
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$3(CrashReportExtender.java:87)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:78)
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:191)
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:494)
	at net.minecraft.util.Util.func_215077_a(SourceFile:404)
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:490)
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:113)

-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.ResourceLoadProgressGui
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:480)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:584)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Linux (amd64) version 5.8.6-1-MANJARO
	Java Version: 14.0.2, N/A
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 452489000 bytes (431 MB) / 1174405120 bytes (1120 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 8 total; -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.2-33.0.42.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.2-33.0.42.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.16.2-33.0.42.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.2-33.0.42.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.2-33.0.42.jar fml TRANSFORMATIONSERVICE 
	FML: 33.0
	Forge: net.minecraftforge:33.0.42
	FML Language Providers: 
		javafml@33.0
		minecraft@1
	Mod List: 
		forge-1.16.2-33.0.42-client.jar Minecraft {minecraft@1.16.2 NONE}
		forge-1.16.2-33.0.42-universal.jar Forge {forge@33.0.42 NONE}
		Xaeros_Minimap_FP20.21.0_Forge_1.16.2.jar Xaero's Minimap Fair-Play {xaerominimapfair@20.21.0 NONE}
		light-overlay-5.5.3.jar Light Overlay Forge {lightoverlay-forge@NONE NONE}
	Launched Version: 1.16.2-forge-33.0.42
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD RENOIR (DRM 3.38.0, 5.8.6-1-MANJARO, LLVM 10.0.1) GL version 4.6 (Compatibility Profile) Mesa 20.1.7, X.Org
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 PRO 4650U with Radeon Graphics
```
