### ISSUE TITLE
Crashing in 1.16.4 

### ISSUE THREAD

**Issue by mdedmon** [shedaniel/LightOverlay-Fabric#68]
I've been using this with optifine and optifabric since the 1.16.1 version. But, after updating mods to 1.16.4, I'm getting a crash with the latest LightOverlay mod installed. Removing it works. I'm including the log file to see if that's any help.

> MultiMC version: 0.6.11-1370

Minecraft folder is:
/Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/instances/20w06a/.minecraft

Java path is:
/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java

Java is version 1.8.0_251, using 64-bit architecture.

Main Class:
  net.fabricmc.loader.launch.knot.KnotClient

Native path:
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/instances/20w06a/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/com/mojang/patchy/1.1/patchy-1.1.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/com/mojang/authlib/2.0.27/authlib-2.0.27.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/net/fabricmc/intermediary/1.16.4/intermediary-1.16.4.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/net/fabricmc/tiny-remapper/0.3.0.70/tiny-remapper-0.3.0.70.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/net/fabricmc/access-widener/1.0.0/access-widener-1.0.0.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/com/google/jimfs/jimfs/1.2-fabric/jimfs-1.2-fabric.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm/9.0/asm-9.0.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm-analysis/9.0/asm-analysis-9.0.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm-commons/9.0/asm-commons-9.0.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm-tree/9.0/asm-tree-9.0.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/ow2/asm/asm-util/9.0/asm-util-9.0.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/net/fabricmc/fabric-loader/0.10.8/fabric-loader-0.10.8.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/com/mojang/minecraft/1.16.4/minecraft-1.16.4-client.jar

Native libraries:
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-macos.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-macos.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-macos.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-macos.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-macos.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-macos.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-macos.jar
  /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0-natives-osx.jar

Mods:
  [✔️] chat-up-1.0.0-1.16
  [✔️] fabricmod_VoxelMap-1.10.14_for_1.16.4
  [✔️] hscroll-1.16.2.001.jar
  [✔️] inventoryprofiles-fabric-1.16.2-0.4.2
  [✔️] light-overlay-5.5.4
  [✔️] modmenu-1.14.13+build.19
  [✔️] optifabric-1.8.10
  [✔️] OptiFine_1.16.4_HD_U_G5_MOD
  [✔️] replaymod-1.16.4-2.5.1
  [✔️] shulkerboxtooltip-2.3.3+1.16.4

Params:
  --username  --version MultiMC5 --gameDir /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/instances/20w06a/.minecraft --assetsDir /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: 1920 x 1080

Java Arguments:
[-Xdock:icon=icon.png, -Xdock:name="MultiMC: 1.16.4", -XstartOnFirstThread, -Xms2048m, -Xmx6144m, -Duser.language=en]

Minecraft process ID: 27682

Using onesix launcher.

[00:20:51] [main/INFO]: Loading for game Minecraft 1.16.4
[00:20:51] [ForkJoinPool-1-worker-1/WARN]: The mod "shulkerboxtooltip" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 8 column 12
[00:20:51] [ForkJoinPool-1-worker-3/WARN]: Non-Fabric mod JAR at "/Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/instances/20w06a/.minecraft/mods/OptiFine_1.16.4_HD_U_G5_MOD.jar", ignoring
[00:20:51] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-resource-loader-v0: used 0.3.1+facf3bbf3a, also found 0.3.1+facf3bbf95
[00:20:51] [main/INFO]: [FabricLoader] Loading 21 mods: minecraft@1.16.4, mm@2.1, fabric-resource-loader-v0@0.3.1+facf3bbf3a, fabric-keybindings-v0@0.2.0+3fa9f7c53a, autoconfig1u@3.3.1, modmenu@1.14.13+build.19, cloth-basic-math@0.5.1, fabricloader@0.10.8, inventoryprofiles@0.4.2, optifabric@1.8.10, lightoverlay@5.5.4, cloth-client-events-v0@1.0.8, voxelmap@1.10.14, hscroll@1.16.2.001.jar, shulkerboxtooltip@2.3.3+1.16.4, fabric-api-base@0.2.0+9f0fb4b83a, fabric-networking-v0@0.1.10+e00ecb5f3a, fabric-key-binding-api-v1@1.0.1+730711c63a, chat-up@1.0, cloth-config2@4.8.2, replaymod@1.16.4-2.5.1
[00:20:51] [main/WARN]: Mod `hscroll` (1.16.2.001.jar) does not respect SemVer - comparison support is limited.
[00:20:51] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[00:20:51] [main/WARN]: Reference map 'mixins.nonmmlauncher.replaymod.refmap.json' for mixins.nonmmlauncher.replaymod.json could not be read. If this is a development environment you can ignore this message
Found existing patched optifine jar, using that
Fetching https://api.sk1er.club/modcore_versions
No ModCore target for 1.16.4_fabric. This in fine, unless you're specifically looking for ModCore.
Replay Mod is still using the traditional Early Riser initialisation
[00:20:52] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[00:20:53] [main/INFO]: [OptiFine] (Reflector) Field not found: World.tileEntitiesToBeRemoved
[00:20:58] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[00:20:58] [main/INFO]: Setting user: Frank_n_Honest
[00:20:58] [main/INFO]: Definitely not up to no good
[00:20:59] [main/INFO]: Mod 'inventoryprofiles' uses the modmenu:clientsideOnly custom value unnecessarily, as it can be inferred from the mod's declared environment.
[00:20:59] [main/INFO]: Mod 'lightoverlay' uses the modmenu:clientsideOnly custom value unnecessarily, as it can be inferred from the mod's declared environment.
[00:20:59] [main/INFO]: Mod 'replaymod' uses the modmenu:clientsideOnly custom value unnecessarily, as it can be inferred from the mod's declared environment.
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 11/28/20 12:21 AM
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'lightoverlay'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/event/lifecycle/v1/ClientTickEvents
	at me.shedaniel.lightoverlay.fabric.LightOverlay.registerClientTick(LightOverlay.java:28)
	at me.shedaniel.lightoverlay.common.fabric.LightOverlayCore.register(LightOverlayCore.java:159)
	at me.shedaniel.lightoverlay.fabric.LightOverlay.onInitializeClient(LightOverlay.java:18)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
	... 19 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:168)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 23 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:33)
	at net.minecraft.class_310.<init>(class_310.java:437)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Mac OS X (x86_64) version 10.15.7
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3327757712 bytes (3173 MB) / 4015521792 bytes (3829 MB) up to 5726797824 bytes (5461 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xms2048m -Xmx6144m
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.16.4_HD_U_G5
	OptiFine Build: 20201106-171901
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 0

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.16.4
	OptiFine jar version: OptiFine_1.16.4_HD_U_G5
	OptiFine jar status: Valid OptiFine mod
	OptiFine remapped jar: /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/instances/20w06a/.minecraft/.optifine/OptiFine_1.16.4_HD_U_G5/Optifine-mapped.jar
	OptiFabric error: <None>
#@!@# Game crashed! Crash report saved to: #@!@# /Users/mikededmon/Desktop/MultiMC.app/Contents/MacOS/instances/20w06a/.minecraft/crash-reports/crash-2020-11-28_00.21.00-client.txt
Process exited with code 255.
Clipboard copy at: 28 Nov 2020 00:23:57 -0500

**Comment by shedaniel** [comment]
Install Fabric API
