### ISSUE TITLE
20w51a - NoSuchMethodError

### ISSUE THREAD

**Issue by mccormackm** [shedaniel/LightOverlay-Fabric#73]
Hey, 

Not sure where this belongs to. The mod loads fine on 1.17, but when pressing F7 to activate it gives the following error message: 

me.shedaniel.lightoverlay.fabric.LightOverlay
main

```javascript

Throwing
java.lang.NoSuchMethodError: net.minecraft.class_2248.method_9525(Lnet/minecraft/class_3494;)Z
	at me.shedaniel.lightoverlay.fabric.LightOverlay.getCrossType(LightOverlay.java:230)
	at me.shedaniel.lightoverlay.fabric.LightOverlay.lambda$static$5(LightOverlay.java:115)
	at me.shedaniel.lightoverlay.fabric.LightOverlay$$Lambda$2542/1551033652.onEndTick(Unknown Source)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents$$Lambda$2456/1060557703.onEndTick(Unknown Source)
	at net.minecraft.class_310.handler$zzm000$onEndTick(class_310.java:2852)
	at net.minecraft.class_310.method_1574(class_310.java:1617)
	at net.minecraft.class_310.method_1523(class_310.java:1026)
	at net.minecraft.class_310.method_1514(class_310.java:688)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

```

I don't know if this has to do with the Fabric API or any other mod, sorry. I saw you was active on GitHub and wanted to try my luck :P

**Comment by shedaniel** [comment]
> The mod loads fine on 1.17

No it does not, the fact that it crashes when it does its things should indicate that this doesn't support 1.17.
