### ISSUE TITLE
Crash while switching worlds

### ISSUE THREAD

**Issue by jorolf** [shedaniel/LightOverlay-Fabric#87]
Whenever the light overlay is enabled and I step into a nether portal my game hard crashes.

Stacktrace:
```
FATAL ERROR in native method: Thread[light-overlay-1,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL11.glDeleteLists(Native Method)
	at me.shedaniel.lightoverlay.common.forge.ChunkData.close(ChunkData.java:128)
	at me.shedaniel.lightoverlay.common.forge.LightOverlay.calculateChunk(LightOverlay.java:248)
	at me.shedaniel.lightoverlay.common.forge.LightOverlay.processChunk(LightOverlay.java:197)
	at me.shedaniel.lightoverlay.common.forge.LightOverlay.lambda$tick$24(LightOverlay.java:612)
	at me.shedaniel.lightoverlay.common.forge.LightOverlay$$Lambda$27064/889142191.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

The modpack I am using is called [Valhelsia 3](https://www.curseforge.com/minecraft/modpacks/valhelsia-3).
The version of Light Overlay I am using is 5.8.0.

If there is anything missing in this report let me know.

**Comment by shedaniel** [comment]
Oops
